FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]

# commands to run:
# docker build -t containerize_react_app -f Dockerfile.dev .
# docker run --rm -d -p 3000:5173 -v ./public:/app/public -v ./src:/app/src containerize_react_app:latest 